In [1]:
import numpy as np
np.__version__

'1.21.1'

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('/data/data.csv')

In [4]:
df.describe().round(2)

Year  Engine HP  Engine Cylinders  Number of Doors  highway MPG  \
count  11914.00   11845.00          11884.00         11908.00     11914.00   
mean    2010.38     249.39              5.63             3.44        26.64   
std        7.58     109.19              1.78             0.88         8.86   
min     1990.00      55.00              0.00             2.00        12.00   
25%     2007.00     170.00              4.00             2.00        22.00   
50%     2015.00     227.00              6.00             4.00        26.00   
75%     2016.00     300.00              6.00             4.00        30.00   
max     2017.00    1001.00             16.00             4.00       354.00   

       city mpg  Popularity        MSRP  
count  11914.00    11914.00    11914.00  
mean      19.73     1554.91    40594.74  
std        8.99     1441.86    60109.10  
min        7.00        2.00     2000.00  
25%       16.00      549.00    21000.00  
50%       18.00     1385.00    29995.00  
75%       22.00     2009.00    42231.25  
max      137.00     5657.00  2065902.00

In [5]:
df.shape[0]

11914

In [6]:
df.groupby('Make').size().sort_values(ascending=False)

Make
Chevrolet        1123
Ford              881
Volkswagen        809
Toyota            746
Dodge             626
Nissan            558
GMC               515
Honda             449
Mazda             423
Cadillac          397
Mercedes-Benz     353
Suzuki            351
BMW               334
Infiniti          330
Audi              328
Hyundai           303
Volvo             281
Subaru            256
Acura             252
Kia               231
Mitsubishi        213
Lexus             202
Buick             196
Chrysler          187
Pontiac           186
Lincoln           164
Oldsmobile        150
Land Rover        143
Porsche           136
Saab              111
Aston Martin       93
Plymouth           82
Bentley            74
Ferrari            69
FIAT               62
Scion              60
Maserati           58
Lamborghini        52
Rolls-Royce        31
Lotus              29
Tesla              18
HUMMER             17
Maybach            16
McLaren             5
Alfa Romeo          5
Spyke

In [7]:
df[df['Make'] == 'Audi'].groupby('Model').count()

Make  Year  Engine Fuel Type  Engine HP  Engine Cylinders  \
Model                                                                        
100                15    15                15         15                15   
200                 6     6                 6          6                 6   
80                  6     6                 6          6                 6   
90                  9     9                 9          9                 9   
A3                 47    47                47         47                47   
A4                 25    25                25         25                25   
A4 allroad          3     3                 3          3                 3   
A5                  9     9                 9          9                 9   
A6                 23    23                23         23                23   
A7                 10    10                10         10                10   
A8                  6     6                 6          6                 6   
Cabriolet           3     3                 3          3                 3   
Coupe               2     2                 2          2                 2   
Q3                 14    14                14         14                14   
Q5                 20    20                20         20                20   
Q7                 15    15                15         15                15   
R8                 25    25                25         25                25   
RS 4                3     3                 3          3                 3   
RS 5                6     6                 6          6                 6   
RS 6                1     1                 1          1                 1   
RS 7                3     3                 3          3                 3   
S3                  6     6                 6          6                 6   
S4                 12    12                12         12                12   
S5                  9     9                 9          9                 9   
S6                  5     5                 5          5                 5   
S7                  4     4                 4          4                 4   
S8                  4     4                 4          4                 4   
SQ5                 6     6                 6          6                 6   
TT                  6     6                 6          6                 6   
TT RS               2     2                 2          2                 2   
TTS                 4     4                 4          4                 4   
V8                  3     3                 3          3                 3   
allroad             8     8                 8          8                 8   
allroad quattro     8     8                 8          8                 8   

                 Transmission Type  Driven_Wheels  Number of Doors  \
Model                                                                
100                             15             15               15   
200                              6              6                6   
80                               6              6                6   
90                               9              9                9   
A3                              47             47               47   
A4                              25             25               25   
A4 allroad                       3              3                3   
A5                               9              9                9   
A6                              23             23               23   
A7                              10             10               10   
A8                               6              6                6   
Cabriolet                        3              3                3   
Coupe                            2              2                2   
Q3                              14             14               14   
Q5                              20             20               20   
Q7                

In [8]:
df[df['Make'] == 'Audi'].nunique()

Make                   1
Model                 34
Year                  20
Engine Fuel Type       5
Engine HP             40
Engine Cylinders       6
Transmission Type      3
Driven_Wheels          2
Number of Doors        2
Market Category       15
Vehicle Size           3
Vehicle Style          6
highway MPG           23
city mpg              18
Popularity             1
MSRP                 234
dtype: int64

In [9]:
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [10]:
df['Engine Cylinders'].describe()

count    11884.000000
mean         5.628829
std          1.780559
min          0.000000
25%          4.000000
50%          6.000000
75%          6.000000
max         16.000000
Name: Engine Cylinders, dtype: float64

In [11]:
cyl_median = df['Engine Cylinders'].median()
cyl_median

6.0

In [12]:
cyl_mode = df['Engine Cylinders'].mode()
cyl_mode

0    4.0
Name: Engine Cylinders, dtype: float64

In [13]:
df['Engine Cylinders'] = df['Engine Cylinders'].fillna(4.0)
df['Engine Cylinders']

0        6.0
1        6.0
2        6.0
3        6.0
4        6.0
        ... 
11909    6.0
11910    6.0
11911    6.0
11912    6.0
11913    6.0
Name: Engine Cylinders, Length: 11914, dtype: float64

In [14]:
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders        0
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [15]:
new_cyl_median = df['Engine Cylinders'].median()
new_cyl_median

6.0

In [16]:
new_cyl_mode = df['Engine Cylinders'].mode()
new_cyl_mode

0    4.0
Name: Engine Cylinders, dtype: float64

In [17]:
df['Engine Cylinders'].describe()

count    11914.000000
mean         5.624727
std          1.780189
min          0.000000
25%          4.000000
50%          6.000000
75%          6.000000
max         16.000000
Name: Engine Cylinders, dtype: float64

In [18]:
lotus_df = df[df['Make'] == 'Lotus']
lotus_df

Make      Model  Year                Engine Fuel Type  Engine HP  \
3912  Lotus      Elise  2009     premium unleaded (required)      189.0   
3913  Lotus      Elise  2009     premium unleaded (required)      218.0   
3914  Lotus      Elise  2009     premium unleaded (required)      189.0   
3915  Lotus      Elise  2010     premium unleaded (required)      189.0   
3916  Lotus      Elise  2010     premium unleaded (required)      218.0   
3917  Lotus      Elise  2011     premium unleaded (required)      189.0   
3918  Lotus      Elise  2011     premium unleaded (required)      217.0   
3919  Lotus      Elise  2011     premium unleaded (required)      217.0   
4216  Lotus     Esprit  2002     premium unleaded (required)      350.0   
4217  Lotus     Esprit  2003     premium unleaded (required)      350.0   
4218  Lotus     Esprit  2004     premium unleaded (required)      350.0   
4257  Lotus  Evora 400  2017     premium unleaded (required)      400.0   
4258  Lotus  Evora 400  2017     premium unleaded (required)      400.0   
4259  Lotus      Evora  2011     premium unleaded (required)      276.0   
4260  Lotus      Evora  2011     premium unleaded (required)      276.0   
4261  Lotus      Evora  2013     premium unleaded (required)      276.0   
4262  Lotus      Evora  2013     premium unleaded (required)      345.0   
4263  Lotus      Evora  2013     premium unleaded (required)      345.0   
4264  Lotus      Evora  2013     premium unleaded (required)      276.0   
4265  Lotus      Evora  2014     premium unleaded (required)      345.0   
4266  Lotus      Evora  2014     premium unleaded (required)      276.0   
4267  Lotus      Evora  2014     premium unleaded (required)      345.0   
4268  Lotus      Evora  2014     premium unleaded (required)      276.0   
4292  Lotus      Exige  2009  premium unleaded (recommended)      257.0   
4293  Lotus      Exige  2009  premium unleaded (recommended)      240.0   
4294  Lotus      Exige  2010  premium unleaded (recommended)      240.0   
4295  Lotus      Exige  2011  premium unleaded (recommended)      240.0   
4296  Lotus      Exige  2011  premium unleaded (recommended)      257.0   
4297  Lotus      Exige  2011  premium unleaded (recommended)      257.0   

      Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
3912               4.0            MANUAL  rear wheel drive              2.0   
3913               4.0            MANUAL  rear wheel drive              2.0   
3914               4.0            MANUAL  rear wheel drive              2.0   
3915               4.0            MANUAL  rear wheel drive              2.0   
3916               4.0            MANUAL  rear wheel drive              2.0   
3917               4.0            MANUAL  rear wheel drive              2.0   
3918               4.0            MANUAL  rear wheel drive              2.0   
3919               4.0            MANUAL  rear wheel drive              2.0   
4216               8.0            MANUAL  rear wheel drive              2.0   
4217               8.0            MANUAL  rear wheel drive              2.0   
4218               8.0            MANUAL  rear wheel drive              2.0   
4257               6.0            MANUAL  rear wheel drive              2.0   
4258               6.0            MANUAL  rear wheel drive              2.0   
4259               6.0            MANUAL  rear wheel drive              2.0   
4260               6.0            MANUAL  rear wheel drive              2.0   
4261               6.0            MANUAL  rear wheel drive              2.0   
4262               6.0            MANUAL  rear wheel drive              2.0   
4263               6.0            MANUAL  rear wheel drive              2.0   
4264               6.0            MANUAL  rear wheel drive              2.0   
4265               6.0            MANUAL  rear wheel drive              2.0   
4266               6.0            MANUAL  rear wheel drive              2.0   
4267              

In [19]:
lotus_df[['Engine HP','Engine Cylinders']]

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3914      189.0               4.0
3915      189.0               4.0
3916      218.0               4.0
3917      189.0               4.0
3918      217.0               4.0
3919      217.0               4.0
4216      350.0               8.0
4217      350.0               8.0
4218      350.0               8.0
4257      400.0               6.0
4258      400.0               6.0
4259      276.0               6.0
4260      276.0               6.0
4261      276.0               6.0
4262      345.0               6.0
4263      345.0               6.0
4264      276.0               6.0
4265      345.0               6.0
4266      276.0               6.0
4267      345.0               6.0
4268      276.0               6.0
4292      257.0               4.0
4293      240.0               4.0
4294      240.0               4.0
4295      240.0               4.0
4296      257.0               4.0
4297      257.0               4.0

In [20]:
X = lotus_df[['Engine HP','Engine Cylinders']].drop_duplicates()
X

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [21]:
X = X.values

In [22]:
X.T

array([[189., 218., 217., 350., 400., 276., 345., 257., 240.],
       [  4.,   4.,   4.,   8.,   6.,   6.,   6.,   4.,   4.]])

In [23]:
XTX = np.matmul(X.T,X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [24]:
np.linalg.det(XTX)
#XTX.shape
#XTX_inv = np.linalg.inv(XTX)

4556268.000000008

In [25]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [26]:
y = np.array([1100,800,750,850,1300,1000,1000,1300,800])

In [27]:
w = np.matmul(XTX_inv,X.T).dot(y) 
w

array([  4.59494481, -63.56432501])