In [1]:
import numpy as np

In [2]:
u = np.array([2,3,5,6])

In [4]:
u

array([2, 3, 5, 6])

In [5]:
2 * u

array([ 4,  6, 10, 12])

In [6]:
v = np.array([1,0,0,2])

In [7]:
v

array([1, 0, 0, 2])

In [8]:
u+v

array([3, 3, 5, 8])

In [11]:
u*v

array([ 2,  0,  0, 12])

In [13]:
np.linalg.multi_dot([u,v])

14

In [14]:
u.dot(v)

14

In [15]:
U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1],
])

In [16]:
U.shape

(3, 4)

In [28]:
def matrix_vector_mult(M, v):
    assert M.shape[1] == v.shape[0]
    
    k = M.shape[0]
    
    result = np.zeros(k)
    
    for i in range(k):
        result[i] = M[i].dot(v)
        
    return result

In [29]:
matrix_vector_mult(U, v)

array([14.,  5.,  5.])

In [30]:
U.dot(v)

array([14,  5,  5])

In [31]:
V = np.array([
    [1,1,2],
    [0,0.5,1],
    [0,2,1],
    [2,1,0],
])

In [39]:
def matrix_matrix_mult(U,V):
    #assert U.shape[0] == V.shape[1]
    assert U.shape[1] == V.shape[0]
    
    rows = U.shape[0]
    cols = V.shape[1]
    
    result = np.zeros(rows, cols)
    
    for i in range(num_cols):
        vi = V[:,i]
        Uvi = U.dot(vi)
        
        result[i] = Uvi
        
    return result

In [43]:
I = np.eye(10)
I

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [46]:
V = np.array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
        [0,2,1],
       [2. , 1. , 0. ]])
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [47]:
Vs = V[[0,1,2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [50]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [51]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])