In [1]:
import numpy as np

In [3]:
np

<module 'numpy' from '/home/pymlboot/anaconda3/envs/ml-zoomcamp/lib/python3.8/site-packages/numpy/__init__.py'>

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [8]:
a = np.array([1,2,3,5,7,12])
a

array([ 1,  2,  3,  5,  7, 12])

In [9]:
a[2]

3

In [10]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [11]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [12]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [16]:
n[0,1]

2

In [17]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
n[2]

array([7, 8, 9])

In [19]:
n[:,2] = [0,1,2]

In [20]:
n

array([[1, 2, 0],
       [4, 5, 1],
       [7, 8, 2]])

In [22]:
np.random.seed(2)
100*np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [23]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [26]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [28]:
b = (10 + (a*2)) ** 2 / 100

In [29]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [30]:
a / b + 100

array([100.        , 100.69444444, 101.02040816, 101.171875  ,
       101.2345679 ])

In [31]:
a

array([0, 1, 2, 3, 4])

In [32]:
a >= 2

array([False, False,  True,  True,  True])

In [33]:
a == 2

array([False, False,  True, False, False])

In [36]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [37]:
a > b

array([False, False,  True,  True,  True])

In [38]:
a[a>b]

array([2, 3, 4])

In [39]:
a

array([0, 1, 2, 3, 4])

In [40]:
a.std()

1.4142135623730951

In [41]:
n.min()

0